apiVersion: v1                           # Core API version
kind: Pod                                # Kubernetes Pod resource
metadata:
  name: demo-secret-env-pod              # Pod name
  labels:
    app: demo-secret-env-pod             # App label value
spec:
  restartPolicy: Never                   # Do not restart Pod
  containers:
    - name: demo-nginx                   # Single container name
      image: nginx:latest                # Demo image tag
      ports:
        - name: http                     # Port label
          containerPort: 80              # Default nginx port
          protocol: TCP                  # Network protocol
      env:                               # Environment variables
        - name: SECRET_USERNAME          # Env var name
          valueFrom:
            secretKeyRef:                # Reference to Secret key
              name: demo-secret-env      # Secret resource name
              key: username              # Secret data key
        - name: SECRET_PASSWORD          # Env var name
          valueFrom:
            secretKeyRef:                # Reference to Secret key
              name: demo-secret-env      # Secret resource name
              key: password              # Secret data key