apiVersion: v1                       # Core API version
kind: Pod                            # Kubernetes Pod resource
metadata:
  name: demo-read-pod                # Pod name
  labels:
    app: demo-read-pod               # App label value
spec:
  containers:
    - name: demo-nginx               # Single container name
      image: nginx:latest            # Demo image tag
      ports:
        - name: http                 # Port label
          containerPort: 80          # Default nginx port
          protocol: TCP              # Network protocol
      livenessProbe:                 # Container health check
        httpGet:
          path: /                    # Probe path
          port: 80                   # Probe port
        initialDelaySeconds: 10      # Delay before start
        periodSeconds: 10            # Check interval
      readinessProbe:                # Traffic readiness check
        httpGet:
          path: /                    # Probe path
          port: 80                   # Probe port
        initialDelaySeconds: 5       # Delay before start
        periodSeconds: 5             # Check interval